### PR TITLE
Fix pickle issue in python2.7

### PR DESCRIPTION
**Pull request by weixuanfu**
1. remove redundant codes in MultiSurfStar and Reliefpercent

2. remove instancemethods in the two classes for better pickling.

### CODE REVIEW

**Comment by weixuanfu** [comment]
Note: I removed both `_compute_score_near` and `_compute_score_far` functions in `MultiSurfStar` because `_compute_score_near` is the same as the `compute_score` in `scoring_utils.py` and only has 4 different lines with `_compute_score_far`.

**Comment by weixuanfu** [comment]
Note: clean up `joblib` in travis-ci since I use `joblib` within `scikit-learn`

**Comment by rhiever** [comment]
>Note: I removed both _compute_score_near and _compute_score_far functions in MultiSurfStar because _compute_score_near is the same as the compute_score in scoring_utils.py and only has 4 different lines with _compute_score_far.

Those 4 differences are significant for that algorithm, however, and must remain for MultiSURF*.

**Comment by rhiever** [comment]
Thanks @weixuanfu!

**Comment by weixuanfu** [comment]
Right, so I added an parameter `near` in `compute_score` for supporting it. Check this link for scores function of MultiSURF*.

https://github.com/EpistasisLab/scikit-rebate/blob/development/skrebate/scoring_utils.py#L213

From my iPhone

On Oct 21, 2017, at 9:39 AM, Randy Olson <notifications@github.com<mailto:notifications@github.com>> wrote:


Note: I removed both _compute_score_near and _compute_score_far functions in MultiSurfStar because _compute_score_near is the same as the compute_score in scoring_utils.py and only has 4 different lines with _compute_score_far.

Those 4 differences are significant for that algorithm, however, and must remain for MultiSURF*.

**Comment by weixuanfu** [comment]
No problem.

From my iPhone

On Oct 21, 2017, at 9:39 AM, Randy Olson <notifications@github.com<mailto:notifications@github.com>> wrote:


Note: I removed both _compute_score_near and _compute_score_far functions in MultiSurfStar because _compute_score_near is the same as the compute_score in scoring_utils.py and only has 4 different lines with _compute_score_far.

Those 4 differences are significant for that algorithm, however, and must remain for MultiSURF*.

**Comment by weixuanfu** [comment]
No problem!

**Comment by rhiever** [comment]
Saw that after I commented. :-)

**Pull request merged**
