### PR TITLE
Implement n_jobs from TuRF to the core_algorithm 

### PR DESCRIPTION
**Pull request by garciaev**
Right now, the core_algorithm in TuRF doesn't get the n_jobs parameter.

### CODE REVIEW

**Comment by rhiever** [comment]
Was this a mistaken PR?

**Comment by garciaev** [comment]
Yes it was - I am not sure how to do a proper PR to solve the issue that turf.py doesn't pass n_jobs to the core_algorithm (i.e core variable in lines 85, 88 of turf.py etc).

**Comment by rhiever** [comment]
That's new TuRF logic that was implemented recently, I believe. I'm actually not sure why TuRF was implemented as a separate class because TuRF is achieve by using the scikit-learn RFE class.

@ryanurbs?

**Comment by ryanurbs** [comment]
We implemented TuRF as a separate class so that we had more control over how it worked, to match previous implementations, that just the scikit-learn RFE didn't seem to match.  Additionally, we are implementing a variety of iterative approaches that will eventually be integrated into scikit-rebate alongside of TuRF.

Regarding the PR issue, you are having, i'm not sure what problem it is you are having.
________________________________

**Comment by rhiever** [comment]
@ryanurbs, I believe the issue @garciaev is raising is that the `n_jobs` parameter isn't being sent to the "core algorithm" of TuRF, nor are any parameters that are provided to TuRF being sent to the "core algorithm."

**Comment by ryanurbs** [comment]
@garciaev, I've recently updated the master and development branches.  If you submit a pull request to the development branch i'll go through and resolve any issues involved with integrating your suggested fix to TuRF with n_jobs.

**Pull request closed without merging**
